.TH _PRINTF 3 _printf\-0.1
.SH NAME
_printf - formatted output
.SH SYNOPSIS
.B #include\ "main.h"

.B int _printf(const char
*format, ...);
.P
.SH DESCRIPTION
The function _printf() produces output according to a format specified in the arguments, as described below:
.TP
.B %d
prints intergers
.TP
.B %f
prints float intergers
.TP
.B %i
prints unsigned intergers
.TP
.B %c
prints characters
.TP
.B %s
prints a string
.SH AUTHOR
 Hector J. Vazquez & Christian Rosario
.SH COPYRIGHT
.B GNU PRINTF Copyright, 2023
